package org.example.MathEditPage.SymbolPanel;

import org.example.MathEditPage.MathButton;
import org.example.MathEditPage.MathPageConstant;

public class GreekSymbolPanel extends SymbolPanel {
    public GreekSymbolPanel() {
        super();
    }

    @Override
    protected void setButton() {
        MathButton alphaButton = new MathButton();
        alphaButton.createButton("\\alpha", MathPageConstant.LATEX_FONT_SIZE);
        MathButton betaButton = new MathButton();
        betaButton.createButton("\\beta", MathPageConstant.LATEX_FONT_SIZE);
        MathButton gammaButton = new MathButton();
        gammaButton.createButton("\\gamma", MathPageConstant.LATEX_FONT_SIZE);
        MathButton deltaButton = new MathButton();
        deltaButton.createButton("\\delta", MathPageConstant.LATEX_FONT_SIZE);
        MathButton epsilonButton = new MathButton();
        epsilonButton.createButton("\\epsilon", MathPageConstant.LATEX_FONT_SIZE);
        MathButton zetaButton = new MathButton();
        zetaButton.createButton("\\zeta", MathPageConstant.LATEX_FONT_SIZE);
        MathButton etaButton = new MathButton();
        etaButton.createButton("\\eta", MathPageConstant.LATEX_FONT_SIZE);
        MathButton thetaButton = new MathButton();
        thetaButton.createButton("\\theta", MathPageConstant.LATEX_FONT_SIZE);
        MathButton iotaButton = new MathButton();
        iotaButton.createButton("\\iota", MathPageConstant.LATEX_FONT_SIZE);
        MathButton kappaButton = new MathButton();
        kappaButton.createButton("\\kappa", MathPageConstant.LATEX_FONT_SIZE);
        MathButton lambdaButton = new MathButton();
        lambdaButton.createButton("\\lambda", MathPageConstant.LATEX_FONT_SIZE);
        MathButton muButton = new MathButton();
        muButton.createButton("\\mu", MathPageConstant.LATEX_FONT_SIZE);
        MathButton nuButton = new MathButton();
        nuButton.createButton("\\nu", MathPageConstant.LATEX_FONT_SIZE);
        MathButton xiButton = new MathButton();
        xiButton.createButton("\\xi", MathPageConstant.LATEX_FONT_SIZE);
        MathButton omicronButton = new MathButton();
        omicronButton.createButton("o", MathPageConstant.LATEX_FONT_SIZE);
        MathButton piButton = new MathButton();
        piButton.createButton("\\pi", MathPageConstant.LATEX_FONT_SIZE);
        MathButton rhoButton = new MathButton();
        rhoButton.createButton("\\rho", MathPageConstant.LATEX_FONT_SIZE);
        MathButton sigmaButton = new MathButton();
        sigmaButton.createButton("\\sigma", MathPageConstant.LATEX_FONT_SIZE);
        MathButton tauButton = new MathButton();
        tauButton.createButton("\\tau", MathPageConstant.LATEX_FONT_SIZE);
        MathButton upsilonButton = new MathButton();
        upsilonButton.createButton("\\upsilon", MathPageConstant.LATEX_FONT_SIZE);
        MathButton phiButton = new MathButton();
        phiButton.createButton("\\phi", MathPageConstant.LATEX_FONT_SIZE);
        MathButton chiButton = new MathButton();
        chiButton.createButton("\\chi", MathPageConstant.LATEX_FONT_SIZE);
        MathButton psiButton = new MathButton();
        psiButton.createButton("\\psi", MathPageConstant.LATEX_FONT_SIZE);
        MathButton omegaButton = new MathButton();
        omegaButton.createButton("\\omega", MathPageConstant.LATEX_FONT_SIZE);

        MathButton AlphaButton = new MathButton();
        AlphaButton.createButton("\\Alpha", MathPageConstant.LATEX_FONT_SIZE);
        MathButton BetaButton = new MathButton();
        BetaButton.createButton("\\Beta", MathPageConstant.LATEX_FONT_SIZE);
        MathButton GammaButton = new MathButton();
        GammaButton.createButton("\\Gamma", MathPageConstant.LATEX_FONT_SIZE);
        MathButton DeltaButton = new MathButton();
        DeltaButton.createButton("\\Delta", MathPageConstant.LATEX_FONT_SIZE);
        MathButton EpsilonButton = new MathButton();
        EpsilonButton.createButton("\\Epsilon", MathPageConstant.LATEX_FONT_SIZE);
        MathButton ZetaButton = new MathButton();
        ZetaButton.createButton("\\Zeta", MathPageConstant.LATEX_FONT_SIZE);
        MathButton EtaButton = new MathButton();
        EtaButton.createButton("\\Eta", MathPageConstant.LATEX_FONT_SIZE);
        MathButton ThetaButton = new MathButton();
        ThetaButton.createButton("\\Theta", MathPageConstant.LATEX_FONT_SIZE);
        MathButton IotaButton = new MathButton();
        IotaButton.createButton("\\Iota", MathPageConstant.LATEX_FONT_SIZE);
        MathButton KappaButton = new MathButton();
        KappaButton.createButton("\\Kappa", MathPageConstant.LATEX_FONT_SIZE);
        MathButton LambdaButton = new MathButton();
        LambdaButton.createButton("\\Lambda", MathPageConstant.LATEX_FONT_SIZE);
        MathButton MuButton = new MathButton();
        MuButton.createButton("\\Mu", MathPageConstant.LATEX_FONT_SIZE);
        MathButton NuButton = new MathButton();
        NuButton.createButton("\\Nu", MathPageConstant.LATEX_FONT_SIZE);
        MathButton XiButton = new MathButton();
        XiButton.createButton("\\Xi", MathPageConstant.LATEX_FONT_SIZE);
        MathButton OmicronButton = new MathButton();
        OmicronButton.createButton("O", MathPageConstant.LATEX_FONT_SIZE);
        MathButton PiButton = new MathButton();
        PiButton.createButton("\\Pi", MathPageConstant.LATEX_FONT_SIZE);
        MathButton RhoButton = new MathButton();
        RhoButton.createButton("\\Rho", MathPageConstant.LATEX_FONT_SIZE);
        MathButton SigmaButton = new MathButton();
        SigmaButton.createButton("\\Sigma", MathPageConstant.LATEX_FONT_SIZE);
        MathButton TauButton = new MathButton();
        TauButton.createButton("\\Tau", MathPageConstant.LATEX_FONT_SIZE);
        MathButton UpsilonButton = new MathButton();
        UpsilonButton.createButton("\\Upsilon", MathPageConstant.LATEX_FONT_SIZE);
        MathButton PhiButton = new MathButton();
        PhiButton.createButton("\\Phi", MathPageConstant.LATEX_FONT_SIZE);
        MathButton ChiButton = new MathButton();
        ChiButton.createButton("\\Chi", MathPageConstant.LATEX_FONT_SIZE);
        MathButton PsiButton = new MathButton();
        PsiButton.createButton("\\Psi", MathPageConstant.LATEX_FONT_SIZE);
        MathButton OmegaButton = new MathButton();
        OmegaButton.createButton("\\Omega", MathPageConstant.LATEX_FONT_SIZE);
        
        buttons.add(alphaButton);
        buttons.add(betaButton);
        buttons.add(gammaButton);
        buttons.add(deltaButton);
        buttons.add(epsilonButton);
        buttons.add(zetaButton);
        buttons.add(etaButton);
        buttons.add(thetaButton);
        buttons.add(iotaButton);
        buttons.add(kappaButton);
        buttons.add(lambdaButton);
        buttons.add(muButton);
        buttons.add(nuButton);
        buttons.add(xiButton);
        buttons.add(omicronButton);
        buttons.add(piButton);
        buttons.add(rhoButton);
        buttons.add(sigmaButton);
        buttons.add(tauButton);
        buttons.add(upsilonButton);
        buttons.add(phiButton);
        buttons.add(chiButton);
        buttons.add(psiButton);
        buttons.add(omegaButton);

        buttons.add(AlphaButton);
        buttons.add(BetaButton);
        buttons.add(GammaButton);
        buttons.add(DeltaButton);
        buttons.add(EpsilonButton);
        buttons.add(ZetaButton);
        buttons.add(EtaButton);
        buttons.add(ThetaButton);
        buttons.add(IotaButton);
        buttons.add(KappaButton);
        buttons.add(LambdaButton);
        buttons.add(MuButton);
        buttons.add(NuButton);
        buttons.add(XiButton);
        buttons.add(OmicronButton);
        buttons.add(PiButton);
        buttons.add(RhoButton);
        buttons.add(SigmaButton);
        buttons.add(TauButton);
        buttons.add(UpsilonButton);
        buttons.add(PhiButton);
        buttons.add(ChiButton);
        buttons.add(PsiButton);
        buttons.add(OmegaButton);
    }
}
